<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-DTOV99D" failures="1" tests="3" name="Default test" time="21.483" errors="0" timestamp="2021-09-24T20:43:33 IST">
  <testcase classname="LoginTestPage.LoginTestPageGitHub" name="create_account" time="13.703"/>
  <testcase classname="LoginTestPage.LoginTestPageGitHub" name="reset_password" time="5.248"/>
  <testcase classname="LoginTestPage.LoginTestPageGitHub" name="login" time="2.362">
    <failure type="java.io.IOException" message="Destination &amp;apos;D:\Bhushan\pageobjectmodel1\GitHubLoginPage\target\screenshot&amp;apos; exists but is a directory">
      <![CDATA[java.io.IOException: Destination 'D:\Bhushan\pageobjectmodel1\GitHubLoginPage\target\screenshot' exists but is a directory
at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:1300)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:797)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:747)
at Base.BaseClass.screenShot(BaseClass.java:51)
at LoginTestPage.LoginTestPageGitHub.login(LoginTestPageGitHub.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Default test -->
